### ISSUE TITLE
Handle renamed projects

### ISSUE THREAD

**Issue by intracer** [scalacenter/scaladex#388] opened 2017-02-14 09:31 UTC
Example:
https://index.scala-lang.org/nrinaudo/kantan.csv
https://index.scala-lang.org/nrinaudo/tabulate
are the same project

**Comment by heathermiller** [comment] 2017-02-14 11:28
Oh shoot, good point. Good catch!

**Comment by MasseGuillaume** [comment] 2017-02-14 12:18
Hey @intracer thanks for letting us know.

It's a duplicate of #95

**Closed by MasseGuillaume** 2017-02-14 12:18 UTC
