### ISSUE TITLE
uPickle page getting a redirection loop?

### ISSUE THREAD

**Issue by jducoeur** [scalacenter/scaladex#534] opened 2018-03-26 15:56 UTC
When I try to go to [the upickle-pprint project in Scaladex](https://index.scala-lang.org/lihaoyi/upickle-pprint), my browser (current Chrome, running on Windows) throws up an error:

> This page isn’t working

> index.scala-lang.org redirected you too many times.

> Try clearing your cookies.

> ERR_TOO_MANY_REDIRECTS

The issue repros when I open an incognito window, so I don't *think* cookies are involved.

**Comment by adpi2** [comment] 2022-01-19 13:26
Probably that was caused by `upickle` being renamed several time back and forth, or maybe because the capitalization changed.

It seems to be fixed now: https://index.scala-lang.org/com-lihaoyi/upickle/upickle/1.4.3?target=_3

**Closed by adpi2** 2022-01-19 13:26 UTC
