### ISSUE TITLE
Invalid query causes an internal server error

### ISSUE THREAD

**Issue by takezoe** [scalacenter/scaladex#253] opened 2016-08-18 02:17 UTC
Invalid query (e.g. including special character such as `]`) causes an internal server error.
![2016-08-18 11 16 03](https://cloud.githubusercontent.com/assets/1094760/17759761/493ab076-6535-11e6-987e-2c503d7c24f4.png)

**Comment by MasseGuillaume** [comment] 2016-08-18 14:30
Hi thanks for the report. It's a duplicate of #196

**Closed by MasseGuillaume** 2016-08-18 14:30 UTC
