### ISSUE TITLE
Filters seems widening search instead of narrowing

### ISSUE THREAD

**Issue by exoego** [scalacenter/scaladex#577] opened 2019-08-15 12:17 UTC
https://index.scala-lang.org/search?q=sbt-scalajs-crossproject shows an expected result (1 exact match project).
![image](https://user-images.githubusercontent.com/127635/63093873-b6dbaa80-bfa1-11e9-91c0-44d7d6501728.png)

However, if I use `Filters` in sidebar to narrow search results, it widen search results.
I think this is not an expected be behavior for search filters.
https://index.scala-lang.org/search?q=sbt-scalajs-crossproject&scalaVersions=2.12
![image](https://user-images.githubusercontent.com/127635/63093923-e1c5fe80-bfa1-11e9-8781-6eab44561e54.png)

# Expected behavior

I expect `Filters` should narrow search results, so one can search projects specific to scala version, scala-js version, or something like that.

**Comment by julienrf** [comment] 2019-09-30 15:12
I’m closing it since it’s a duplicate of #473, but thanks for the detailed report with screenshots!

**Closed by julienrf** 2019-09-30 15:12 UTC
