### ISSUE TITLE
An admin of a repository should have the permission to edit settings for the repository on Scaladex

### ISSUE THREAD

**Issue by Atry** [scalacenter/scaladex#316] opened 2017-01-01 10:33 UTC
I am one of the admin of https://github.com/ThoughtWorksInc/DeepLearning.scala, I expect that I can access https://index.scala-lang.org/edit/thoughtworksinc/deeplearning.scala , however, the page always shows a `Forbidden` for me .

**Comment by heathermiller** [comment] 2017-01-02 08:45
Ah, it must be the `.` in the name... 

I suspect it's a quick fix! @MasseGuillaume WDYT?

**Comment by MasseGuillaume** [comment] 2017-01-02 19:17
hum yep it's because of some routing priority

**Comment by vossad01** [comment] 2017-01-07 23:04
I was not able to reproduce any issues with a `.` in the name locally.

The page is accessible, so no issue with the Akka HTTP routing.  Repositories of mine with a `.` in the name appear correctly my UserState and `deeplearning.scala` is presented correctly with the dot in the name as the `repo`.

@Atry When you first signed in to Scaladex, did you grant it access to the "ThoughtWorksInc" organization?  You would have needed to explicitly click on the grant button.  Without doing so, Scaladex will not see any repositories under that organization when looking at your GitHub account.

**Comment by Atry** [comment] 2017-01-07 23:08
I guess I have grant the access to "ThoughtWorksInc" organization.

I am both the admin of https://github.com/ThoughtWorksInc/Binding.scala and https://github.com/ThoughtWorksInc/DeepLearning.scala and I can only access https://index.scala-lang.org/edit/thoughtworksinc/binding.scala . However https://index.scala-lang.org/edit/thoughtworksinc/deeplearning.scala is forbidded.

**Comment by MasseGuillaume** [comment] 2017-01-07 23:31
https://github.com/ThoughtWorksInc has a lot of repositories
we limit it to 5 pages to avoid timeout.
https://github.com/scalacenter/scaladex/blob/master/server/src/main/scala/ch.epfl.scala.index.server/Github.scala#L104

**Comment by Sciss** [comment] 2018-05-01 21:46
Could this please be fixed, issue is open > 1 year. I still can't mark my projects as contributors-wanted, because only 20 out of 200 or so are editable. Thanks!

**Comment by Atry** [comment] 2018-11-20 09:48
Hi, @julienrf , could you reopen this issue ? I still got a `Forbidden` error on https://index.scala-lang.org/edit/thoughtworksinc/deeplearning.scala.

**Comment by mlachkar** [comment] 2021-12-10 10:08
Hello! We fixed this feature on the dev server! https://index-dev.scala-lang.org/ 
Would you like to test that it works for you ? thanks!

**Comment by Atry** [comment] 2021-12-10 18:34
<img width="1233" alt="截屏2021-12-10 上午10 33 56" src="https://user-images.githubusercontent.com/601530/145624315-a824f5c6-e763-4882-93e4-a0950110878d.png">

**Comment by mlachkar** [comment] 2021-12-11 13:34
Thanks for your response! Can you also share with me what do you see in "my projects" (if you click on your name, you can see a dropdown and then the link myprojects )

**Comment by Atry** [comment] 2021-12-11 22:17
<img width="809" alt="截屏2021-12-11 下午2 17 07" src="https://user-images.githubusercontent.com/601530/145693319-f92bed4e-d2ae-43ce-bb32-043761cb1678.png">

**Comment by mlachkar** [comment] 2021-12-13 16:17
I have deployed a new version, and I would like to know if you still have an empty page on `myprojects` https://index-dev.scala-lang.org/ 

Thanks again for your help!

**Comment by Atry** [comment] 2021-12-13 17:18
<img width="1175" alt="截屏2021-12-13 上午9 17 12" src="https://user-images.githubusercontent.com/601530/145858120-9294646a-4d64-4bcc-bb26-c9500eef9769.png">
<img width="1175" alt="截屏2021-12-13 上午9 18 03" src="https://user-images.githubusercontent.com/601530/145858249-d8002ad6-b97a-4770-8436-0f293abd4b39.png">

**Comment by mlachkar** [comment] 2021-12-13 18:08
Thank you for you patience. It working now for those directories. you can check again please.
But for the projects under `ThoughtWorksInc`, it's more complicated.
- first it's not listed under your organizations. we only see 3 organizations: 
```
        "nodes": [
          {
            "name": "The Scala Programming Language"
          },
          {
            "name": "ThoughtWorks-Xi-an-Scala-Camp"
          },
          {
            "name": "haxe-continuation"
          }
        ]
 ``` 
The two last one have enabled OAuth App access restrictions, meaning that data access to third-parties is limited (so we cannot retrieve the repositories name under organization you belong to ) 


This the request we do to retrieve all repos under your organizations. (you can execute yourself if you are interested on github [graphql explorer](https://docs.github.com/en/graphql/overview/explorer)
 
```
query {
  viewer {
    organizations(first: 100) {
      pageInfo {
        endCursor
        hasNextPage
      }
      nodes {
        repositories(first: 100, affiliations: [COLLABORATOR, ORGANIZATION_MEMBER, OWNER]) {
          pageInfo {
            endCursor
            hasNextPage
          }
          nodes {
            nameWithOwner
            viewerPermission
          }
        }
      }
    }
  }
}
``` 

There is still a way to add youself as `Admin` or `Write` for this repo. under settings, there is a tab manage access, you can add youself explicitly.
<img width="1373" alt="Screenshot 2021-12-13 at 19 06 48" src="https://user-images.githubusercontent.com/7843237/145865292-cb1e966e-e39c-4fc8-887b-833b5fc77572.png">


Anyway, I really want to fix this issue, and thank you for helping doing it!

**Comment by mlachkar** [comment] 2021-12-13 18:52
So now, I m quite confident: it should work! 
Please again can you check on preprod! https://index-dev.scala-lang.org/

**Comment by Atry** [comment] 2021-12-13 19:02
<img width="1203" alt="截屏2021-12-13 上午11 02 41" src="https://user-images.githubusercontent.com/601530/145872257-a7b50565-50c9-4983-a196-a18975c3a2f0.png">
It works!

Thank you!

**Comment by mlachkar** [comment] 2021-12-23 15:43
It's now deployed into prod! Happy that this issue is now fixed

**Closed by mlachkar** 2021-12-23 15:43 UTC
Labels: top priority
