### ISSUE TITLE
Search results relevance

### ISSUE THREAD

**Issue by jendakol** [scalacenter/scaladex#551] opened 2018-08-09 13:29 UTC
I think there is still place for better relevance detection for search results.
E.g. why https://index.scala-lang.org/search?q=http+client&targetTypes=Jvm&scalaVersions=2.12 gives `scala/scala` as the first (most relevant) result when it's definitely not an http client?

**Comment by MasseGuillaume** [comment] 2018-08-09 13:39
Duplicate of https://github.com/scalacenter/scaladex/issues/389

**Comment by MasseGuillaume** [comment] 2018-08-09 13:41
If you search for http-client: https://index.scala-lang.org/search?q=http-client&topics=http-client

Scaladex will propose you to use the topic http-client:  https://index.scala-lang.org/search?q=http-client&topics=http-client

**Comment by jendakol** [comment] 2018-08-09 15:21
Well, ok... With the topic it's much better.
But it still doesn't explain the "http client" <-> "scala" relation.

**Comment by adpi2** [comment] 2020-03-30 16:40
Search relevance has been improved since then, by #597.
@jendakol, you should give it a second try.

**Closed** 2020-03-30 17:39 UTC
